[project]
name = "patient-segmentation-bmi"
version = "0.1.0"
description = ""
authors = [
    {name = "diipdata",email = "diegop.freitas@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "notebook (>=7.4.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
